services:

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27000:27017
    volumes:
      - db:/data/chat-db

  chat-server:
    depends_on:
      - mongodb
    build:
      context: ./server
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000

  chat-client:
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

volumes:
  db: